<?php

namespace Database\Seeders;

use App\Models\Doctor;
use App\Models\User;
use App\Models\Specialization;
use App\Models\DoctorSchedule;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class MedicareDoctorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $doctors = [
            // Cardiology Department (5 doctors)
            [
                'name' => 'Prof. Dr. Mahbub Ali',
                'email' => 'mahbub.ali@medicare.local',
                'phone' => '+8801712345681',
                'specialization' => 'Cardiology',
                'qualification' => 'MD, FACC, FSCAI',
                'hospital' => 'National Institute of Chest & Hospital',
                'fee' => 1000,
                'experience_years' => 20,
                'rating' => 4.9,
                'license_number' => 'MD-CARD-001',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 20,
                'city' => 'Dhaka',
                'address' => 'National Institute of Chest & Hospital, Dhaka',
                'bio' => 'Leading cardiologist with 20+ years of experience in interventional cardiology.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. A.K.M. Mosharraf Hossain',
                'email' => 'mosharraf.hossain@medicare.local',
                'phone' => '+8801712345682',
                'specialization' => 'Cardiology',
                'qualification' => 'MD(Cardiology), FCPS, FACC',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 800,
                'experience_years' => 15,
                'rating' => 4.7,
                'license_number' => 'MD-CARD-002',
                'available_days' => ['sunday', 'tuesday', 'thursday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:30:00',
                'max_appointments' => 15,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Expert in cardiac imaging and non-invasive cardiology procedures.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Mohammad Badruddoza',
                'email' => 'badruddoza@medicare.local',
                'phone' => '+8801712345683',
                'specialization' => 'Cardiology',
                'qualification' => 'MD, PhD, FACC',
                'hospital' => 'Apollo Hospitals Dhaka',
                'fee' => 1200,
                'experience_years' => 18,
                'rating' => 4.8,
                'license_number' => 'MD-CARD-003',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '08:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:00:00',
                'break_end' => '12:00:00',
                'max_appointments' => 18,
                'city' => 'Dhaka',
                'address' => 'Apollo Hospitals, Bashundhara, Dhaka',
                'bio' => 'Renowned interventional cardiologist specializing in complex angioplasty.',
                'languages' => ['en', 'bn', 'ar'],
            ],
            [
                'name' => 'Prof. Dr. Fazlur Rahman',
                'email' => 'fazlur.rahman@medicare.local',
                'phone' => '+8801712345684',
                'specialization' => 'Cardiology',
                'qualification' => 'MD(Cardiology), FCPS, FACP',
                'hospital' => 'Sir Salimullah Medical College',
                'fee' => 700,
                'experience_years' => 22,
                'rating' => 4.6,
                'license_number' => 'MD-CARD-004',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 16,
                'city' => 'Dhaka',
                'address' => 'SSMC, Mitford, Dhaka',
                'bio' => 'Experienced cardiologist with expertise in heart failure management.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Shahidullah',
                'email' => 'shahidullah@medicare.local',
                'phone' => '+8801712345685',
                'specialization' => 'Cardiology',
                'qualification' => 'MD, FSCAI, FACC',
                'hospital' => 'National Heart Foundation',
                'fee' => 900,
                'experience_years' => 16,
                'rating' => 4.5,
                'license_number' => 'MD-CARD-005',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '17:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 18,
                'city' => 'Dhaka',
                'address' => 'National Heart Foundation, Dhaka',
                'bio' => 'Specialist in preventive cardiology and cardiac rehabilitation.',
                'languages' => ['en', 'bn'],
            ],

            // Medicine Department (6 doctors)
            [
                'name' => 'Dr. Mahmudul Hasan Khan',
                'email' => 'mahmudul.hasan@medicare.local',
                'phone' => '+8801712345678',
                'specialization' => 'Medicine & Chest Diseases',
                'qualification' => 'MBBS, IDM, CCD, CCCD, MPH, MCCP, MSC',
                'hospital' => 'National Institute of Disease of the Chest & Hospital',
                'fee' => 700,
                'experience_years' => 10,
                'rating' => 4.5,
                'license_number' => 'MD-MED-001',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '16:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 20,
                'city' => 'Dhaka',
                'address' => 'NIDCH, Mohakhali, Dhaka',
                'bio' => 'Expert in respiratory diseases and internal medicine.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Md. Abdul Halim',
                'email' => 'abdul.halim@medicare.local',
                'phone' => '+8801712345679',
                'specialization' => 'Family Medicine',
                'qualification' => 'MBBS(CU), MPH(LU), CCD, EDC',
                'hospital' => 'MRMCH',
                'fee' => 500,
                'experience_years' => 8,
                'rating' => 4.3,
                'license_number' => 'MD-MED-002',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '08:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:00:00',
                'break_end' => '12:00:00',
                'max_appointments' => 25,
                'city' => 'Dhaka',
                'address' => 'MRMCH, Dhaka',
                'bio' => 'Family medicine specialist with focus on preventive healthcare.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Mohammad Kamrul Hasan',
                'email' => 'kamrul.hasan@medicare.local',
                'phone' => '+8801712345680',
                'specialization' => 'Medicine',
                'qualification' => 'FCPS(Medicine), MD(Critical Care Medicine)',
                'hospital' => 'National Institute of Chest & Hospital',
                'fee' => 800,
                'experience_years' => 12,
                'rating' => 4.7,
                'license_number' => 'MD-MED-003',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '10:00:00',
                'end_time' => '18:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 18,
                'city' => 'Dhaka',
                'address' => 'NIDCH, Mohakhali, Dhaka',
                'bio' => 'Critical care specialist with expertise in ICU management.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Prof. Dr. M. A. Jalil Chowdhury',
                'email' => 'jalil.chowdhury@medicare.local',
                'phone' => '+8801712345686',
                'specialization' => 'Medicine',
                'qualification' => 'FCPS(Medicine), FACP, FRCP',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 900,
                'experience_years' => 25,
                'rating' => 4.9,
                'license_number' => 'MD-MED-004',
                'available_days' => ['sunday', 'tuesday', 'thursday'],
                'start_time' => '09:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:30:00',
                'break_end' => '12:30:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Professor of medicine with extensive research experience.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Prodip Kumar Dhar',
                'email' => 'prodip.dhar@medicare.local',
                'phone' => '+8801712345687',
                'specialization' => 'Medicine',
                'qualification' => 'MBBS, FCPS(Medicine), MACP',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 600,
                'experience_years' => 14,
                'rating' => 4.4,
                'license_number' => 'MD-MED-005',
                'available_days' => ['monday', 'wednesday', 'friday', 'saturday'],
                'start_time' => '08:00:00',
                'end_time' => '15:00:00',
                'break_start' => '11:00:00',
                'break_end' => '12:00:00',
                'max_appointments' => 20,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Internal medicine specialist with interest in diabetes management.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. A. K. M. Shaheed',
                'email' => 'shaheed@medicare.local',
                'phone' => '+8801712345688',
                'specialization' => 'Medicine',
                'qualification' => 'MD(Medicine), FACP',
                'hospital' => 'Square Hospitals Ltd.',
                'fee' => 750,
                'experience_years' => 11,
                'rating' => 4.6,
                'license_number' => 'MD-MED-006',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '16:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 18,
                'city' => 'Dhaka',
                'address' => 'Square Hospitals, Dhaka',
                'bio' => 'Specialist in infectious diseases and tropical medicine.',
                'languages' => ['en', 'bn'],
            ],

            // Pediatrics Department (5 doctors)
            [
                'name' => 'Prof. Dr. M. A. K. Azad',
                'email' => 'azad@medicare.local',
                'phone' => '+8801712345689',
                'specialization' => 'Pediatrics',
                'qualification' => 'FCPS(Pediatrics), MD(Pediatrics), DCH',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 800,
                'experience_years' => 20,
                'rating' => 4.8,
                'license_number' => 'MD-PED-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 15,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Expert in pediatric nutrition and growth disorders.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Shirin Afroza',
                'email' => 'shirin.afroza@medicare.local',
                'phone' => '+8801712345690',
                'specialization' => 'Pediatrics',
                'qualification' => 'FCPS(Pediatrics), DCH',
                'hospital' => 'Dhaka Shishu Hospital',
                'fee' => 600,
                'experience_years' => 12,
                'rating' => 4.7,
                'license_number' => 'MD-PED-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 20,
                'city' => 'Dhaka',
                'address' => 'Dhaka Shishu Hospital, Dhaka',
                'bio' => 'Pediatric specialist with expertise in childhood diseases.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Prof. Dr. L. R. Murad',
                'email' => 'murad@medicare.local',
                'phone' => '+8801712345691',
                'specialization' => 'Pediatrics',
                'qualification' => 'FCPS(Pediatrics), FRCP, MD',
                'hospital' => 'Institute of Child Health',
                'fee' => 700,
                'experience_years' => 18,
                'rating' => 4.6,
                'license_number' => 'MD-PED-003',
                'available_days' => ['sunday', 'tuesday', 'thursday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '14:00:00',
                'break_start' => '12:00:00',
                'break_end' => '12:30:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'ICH, Dhaka',
                'bio' => 'Specialist in neonatal care and pediatric emergencies.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. A. K. M. Ahsanullah',
                'email' => 'ahsanullah@medicare.local',
                'phone' => '+8801712345692',
                'specialization' => 'Pediatrics',
                'qualification' => 'MD(Pediatrics), FCPS',
                'hospital' => 'Shishu Hospital',
                'fee' => 550,
                'experience_years' => 9,
                'rating' => 4.4,
                'license_number' => 'MD-PED-004',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 15,
                'city' => 'Dhaka',
                'address' => 'Shishu Hospital, Dhaka',
                'bio' => 'Pediatrician focusing on preventive care and vaccinations.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Mahbuba Khan',
                'email' => 'mahbuba.khan@medicare.local',
                'phone' => '+8801712345693',
                'specialization' => 'Pediatrics',
                'qualification' => 'FCPS(Pediatrics), DCH',
                'hospital' => 'Apollo Hospitals Dhaka',
                'fee' => 650,
                'experience_years' => 10,
                'rating' => 4.5,
                'license_number' => 'MD-PED-005',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
                'start_time' => '09:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:30:00',
                'break_end' => '12:00:00',
                'max_appointments' => 16,
                'city' => 'Dhaka',
                'address' => 'Apollo Hospitals, Dhaka',
                'bio' => 'Expert in pediatric allergies and respiratory diseases.',
                'languages' => ['en', 'bn'],
            ],

            // Orthopedics Department (5 doctors)
            [
                'name' => 'Prof. Dr. M. K. B. Nazir',
                'email' => 'nazir@medicare.local',
                'phone' => '+8801712345694',
                'specialization' => 'Orthopedics',
                'qualification' => 'FCPS(Ortho), FICS, AO Fellow',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 1000,
                'experience_years' => 22,
                'rating' => 4.9,
                'license_number' => 'MD-ORTHO-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Leading orthopedic surgeon specializing in joint replacement.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Kazi Shahidullah',
                'email' => 'kazi.shahidullah@medicare.local',
                'phone' => '+8801712345695',
                'specialization' => 'Orthopedics',
                'qualification' => 'FCPS(Ortho), MS(Ortho)',
                'hospital' => 'National Institute of Traumatology & Orthopedic Rehabilitation',
                'fee' => 800,
                'experience_years' => 15,
                'rating' => 4.7,
                'license_number' => 'MD-ORTHO-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 15,
                'city' => 'Dhaka',
                'address' => 'NITOR, Dhaka',
                'bio' => 'Expert in sports medicine and arthroscopic surgery.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. A. K. M. Ziaur Rahman',
                'email' => 'ziaur.rahman@medicare.local',
                'phone' => '+8801712345696',
                'specialization' => 'Orthopedics',
                'qualification' => 'MS(Ortho), FACS',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 600,
                'experience_years' => 12,
                'rating' => 4.5,
                'license_number' => 'MD-ORTHO-003',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Specialist in spine surgery and spinal disorders.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. M. A. Gafur',
                'email' => 'gafur@medicare.local',
                'phone' => '+8801712345697',
                'specialization' => 'Orthopedics',
                'qualification' => 'FCPS(Ortho), AO Trauma Fellow',
                'hospital' => 'Sir Salimullah Medical College',
                'fee' => 700,
                'experience_years' => 14,
                'rating' => 4.6,
                'license_number' => 'MD-ORTHO-004',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'start_time' => '09:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:30:00',
                'break_end' => '12:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'SSMC, Dhaka',
                'bio' => 'Trauma and fracture specialist with expertise in minimally invasive surgery.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. ASM Badruddoza',
                'email' => 'asm.badruddoza@medicare.local',
                'phone' => '+8801712345698',
                'specialization' => 'Orthopedics',
                'qualification' => 'MD(Ortho), PhD',
                'hospital' => 'Square Hospitals Ltd.',
                'fee' => 900,
                'experience_years' => 16,
                'rating' => 4.8,
                'license_number' => 'MD-ORTHO-005',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '10:00:00',
                'end_time' => '17:00:00',
                'break_start' => '13:30:00',
                'break_end' => '14:30:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'Square Hospitals, Dhaka',
                'bio' => 'Pediatric orthopedics specialist and scoliosis expert.',
                'languages' => ['en', 'bn'],
            ],

            // Neurology Department (4 doctors)
            [
                'name' => 'Prof. Dr. Kazi Shahidullah',
                'email' => 'neurology@medicare.local',
                'phone' => '+8801712345699',
                'specialization' => 'Neurology',
                'qualification' => 'FCPS(Neurology), MD(Neurology), FRCP',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 1200,
                'experience_years' => 20,
                'rating' => 4.9,
                'license_number' => 'MD-NEURO-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 10,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Top neurologist with expertise in stroke and epilepsy treatment.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Omar Kamal',
                'email' => 'omar.kamal@medicare.local',
                'phone' => '+8801712345700',
                'specialization' => 'Neurology',
                'qualification' => 'MD(Neurology), FCPS',
                'hospital' => 'National Institute of Neurosciences & Hospital',
                'fee' => 900,
                'experience_years' => 12,
                'rating' => 4.6,
                'license_number' => 'MD-NEURO-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'NINS, Dhaka',
                'bio' => 'Specialist in movement disorders and Parkinson\'s disease.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. A. K. M. Shaheen',
                'email' => 'shaheen@medicare.local',
                'phone' => '+8801712345701',
                'specialization' => 'Neurology',
                'qualification' => 'FCPS(Neurology), MD',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 800,
                'experience_years' => 10,
                'rating' => 4.5,
                'license_number' => 'MD-NEURO-003',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Expert in headache and migraine management.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Prof. Dr. M. H. R. Chowdhury',
                'email' => 'rashed.chowdhury@medicare.local',
                'phone' => '+8801712345702',
                'specialization' => 'Neurology',
                'qualification' => 'PhD(Neurology), FCPS',
                'hospital' => 'Sir Salimullah Medical College',
                'fee' => 850,
                'experience_years' => 18,
                'rating' => 4.7,
                'license_number' => 'MD-NEURO-004',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:00:00',
                'max_appointments' => 10,
                'city' => 'Dhaka',
                'address' => 'SSMC, Dhaka',
                'bio' => 'Specialist in neurophysiology and EMG studies.',
                'languages' => ['en', 'bn'],
            ],

            // Dermatology Department (4 doctors)
            [
                'name' => 'Prof. Dr. Abida Sultana',
                'email' => 'abida.sultana@medicare.local',
                'phone' => '+8801712345703',
                'specialization' => 'Dermatology',
                'qualification' => 'FCPS(Dermatology), MD, DDV',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 800,
                'experience_years' => 18,
                'rating' => 4.8,
                'license_number' => 'MD-DERMA-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:30:00',
                'max_appointments' => 18,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Leading dermatologist with expertise in cosmetic dermatology.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Runa Khan',
                'email' => 'runa.khan@medicare.local',
                'phone' => '+8801712345704',
                'specialization' => 'Dermatology',
                'qualification' => 'FCPS(Dermatology), DDV',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 600,
                'experience_years' => 10,
                'rating' => 4.5,
                'license_number' => 'MD-DERMA-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:30:00',
                'break_end' => '12:00:00',
                'max_appointments' => 20,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Specialist in skin allergies and eczema treatment.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Firoz Khan',
                'email' => 'firoz.khan@medicare.local',
                'phone' => '+8801712345705',
                'specialization' => 'Dermatology',
                'qualification' => 'MD(Dermatology), FCPS',
                'hospital' => 'Square Hospitals Ltd.',
                'fee' => 750,
                'experience_years' => 12,
                'rating' => 4.6,
                'license_number' => 'MD-DERMA-003',
                'available_days' => ['monday', 'wednesday', 'friday', 'saturday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 16,
                'city' => 'Dhaka',
                'address' => 'Square Hospitals, Dhaka',
                'bio' => 'Expert in hair loss treatment and laser therapy.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Nishat Jahan',
                'email' => 'nishat.jahan@medicare.local',
                'phone' => '+8801712345706',
                'specialization' => 'Dermatology',
                'qualification' => 'FCPS(Dermatology), DDV',
                'hospital' => 'Apollo Hospitals Dhaka',
                'fee' => 700,
                'experience_years' => 8,
                'rating' => 4.4,
                'license_number' => 'MD-DERMA-004',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'Apollo Hospitals, Dhaka',
                'bio' => 'Pediatric dermatologist and vitiligo specialist.',
                'languages' => ['en', 'bn'],
            ],

            // Gynecology & Obstetrics Department (5 doctors)
            [
                'name' => 'Prof. Dr. Rashida Begum',
                'email' => 'rashida.begum@medicare.local',
                'phone' => '+8801712345707',
                'specialization' => 'Gynecology & Obstetrics',
                'qualification' => 'FCPS(Gynae), DGO, FICS',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 900,
                'experience_years' => 22,
                'rating' => 4.9,
                'license_number' => 'MD-GYNAE-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 15,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Expert in high-risk pregnancy and laparoscopic surgery.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Halima Begum',
                'email' => 'halima.begum@medicare.local',
                'phone' => '+8801712345708',
                'specialization' => 'Gynecology & Obstetrics',
                'qualification' => 'FCPS(Gynae), DGO',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 650,
                'experience_years' => 14,
                'rating' => 4.7,
                'license_number' => 'MD-GYNAE-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 18,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Specialist in infertility treatment and IVF.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Prof. Dr. Shamim Jahan',
                'email' => 'shamim.jahan@medicare.local',
                'phone' => '+8801712345709',
                'specialization' => 'Gynecology & Obstetrics',
                'qualification' => 'FCPS(Gynae), MD',
                'hospital' => 'Sir Salimullah Medical College',
                'fee' => 750,
                'experience_years' => 18,
                'rating' => 4.8,
                'license_number' => 'MD-GYNAE-003',
                'available_days' => ['sunday', 'tuesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '14:00:00',
                'break_start' => '12:00:00',
                'break_end' => '12:30:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'SSMC, Dhaka',
                'bio' => 'Expert in gynecological oncology and cancer screening.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Shahida Parveen',
                'email' => 'shahida.parveen@medicare.local',
                'phone' => '+8801712345710',
                'specialization' => 'Gynecology & Obstetrics',
                'qualification' => 'FCPS(Gynae), DGO',
                'hospital' => 'Apollo Hospitals Dhaka',
                'fee' => 800,
                'experience_years' => 12,
                'rating' => 4.6,
                'license_number' => 'MD-GYNAE-004',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:30:00',
                'break_end' => '12:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'Apollo Hospitals, Dhaka',
                'bio' => 'Specialist in menopause and hormonal disorders.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Rubaiyat Jahan',
                'email' => 'rubaiyat.jahan@medicare.local',
                'phone' => '+8801712345711',
                'specialization' => 'Gynecology & Obstetrics',
                'qualification' => 'MD(Gynae), FCPS',
                'hospital' => 'Square Hospitals Ltd.',
                'fee' => 700,
                'experience_years' => 10,
                'rating' => 4.5,
                'license_number' => 'MD-GYNAE-005',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 16,
                'city' => 'Dhaka',
                'address' => 'Square Hospitals, Dhaka',
                'bio' => 'Expert in normal delivery and prenatal care.',
                'languages' => ['en', 'bn'],
            ],

            // ENT Department (4 doctors)
            [
                'name' => 'Prof. Dr. Mohammad Ali',
                'email' => 'mohammad.ali@medicare.local',
                'phone' => '+8801712345712',
                'specialization' => 'ENT',
                'qualification' => 'FCPS(ENT), DLO, MS(ENT)',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 850,
                'experience_years' => 20,
                'rating' => 4.8,
                'license_number' => 'MD-ENT-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 15,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Leading ENT specialist with expertise in head and neck surgery.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. A. K. M. Hafiz',
                'email' => 'hafiz@medicare.local',
                'phone' => '+8801712345713',
                'specialization' => 'ENT',
                'qualification' => 'FCPS(ENT), DLO',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 600,
                'experience_years' => 12,
                'rating' => 4.5,
                'license_number' => 'MD-ENT-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:30:00',
                'break_end' => '12:00:00',
                'max_appointments' => 18,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Specialist in hearing loss and cochlear implants.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Kazi M. Hoque',
                'email' => 'hoque@medicare.local',
                'phone' => '+8801712345714',
                'specialization' => 'ENT',
                'qualification' => 'MS(ENT), FCPS',
                'hospital' => 'Sir Salimullah Medical College',
                'fee' => 650,
                'experience_years' => 10,
                'rating' => 4.4,
                'license_number' => 'MD-ENT-003',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'SSMC, Dhaka',
                'bio' => 'Expert in sinus and endoscopic sinus surgery.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. M. M. H. Sarker',
                'email' => 'sarker@medicare.local',
                'phone' => '+8801712345715',
                'specialization' => 'ENT',
                'qualification' => 'FCPS(ENT), DLO',
                'hospital' => 'National Institute of ENT',
                'fee' => 700,
                'experience_years' => 14,
                'rating' => 4.6,
                'license_number' => 'MD-ENT-004',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'NENT, Dhaka',
                'bio' => 'Specialist in voice disorders and laryngeal surgery.',
                'languages' => ['en', 'bn'],
            ],

            // Ophthalmology Department (4 doctors)
            [
                'name' => 'Prof. Dr. Hossain Ali',
                'email' => 'hossain.ali@medicare.local',
                'phone' => '+8801712345716',
                'specialization' => 'Ophthalmology',
                'qualification' => 'FCPS(Eye), MS(Ophthalmology), FRCS',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 900,
                'experience_years' => 22,
                'rating' => 4.9,
                'license_number' => 'MD-OPHTHA-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 15,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Leading ophthalmologist specializing in cataract and LASIK surgery.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. M. A. Khan',
                'email' => 'ma.khan@medicare.local',
                'phone' => '+8801712345717',
                'specialization' => 'Ophthalmology',
                'qualification' => 'FCPS(Eye), DO',
                'hospital' => 'National Institute of Ophthalmology',
                'fee' => 700,
                'experience_years' => 14,
                'rating' => 4.7,
                'license_number' => 'MD-OPHTHA-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 18,
                'city' => 'Dhaka',
                'address' => 'NIO, Dhaka',
                'bio' => 'Expert in retinal diseases and diabetic retinopathy treatment.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Farah Deeba',
                'email' => 'farah.deeba@medicare.local',
                'phone' => '+8801712345718',
                'specialization' => 'Ophthalmology',
                'qualification' => 'MS(Ophthalmology), FCPS',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 650,
                'experience_years' => 10,
                'rating' => 4.5,
                'license_number' => 'MD-OPHTHA-003',
                'available_days' => ['monday', 'wednesday', 'friday', 'saturday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 16,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Specialist in pediatric ophthalmology and squint treatment.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. M. R. Karim',
                'email' => 'mr.karim@medicare.local',
                'phone' => '+8801712345719',
                'specialization' => 'Ophthalmology',
                'qualification' => 'FCPS(Eye), MS',
                'hospital' => 'Apollo Hospitals Dhaka',
                'fee' => 800,
                'experience_years' => 12,
                'rating' => 4.6,
                'license_number' => 'MD-OPHTHA-004',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'Apollo Hospitals, Dhaka',
                'bio' => 'Expert in glaucoma treatment and eye trauma.',
                'languages' => ['en', 'bn'],
            ],

            // Psychiatry Department (4 doctors)
            [
                'name' => 'Prof. Dr. Ahmed H. M. Morshed',
                'email' => 'morshed@medicare.local',
                'phone' => '+8801712345720',
                'specialization' => 'Psychiatry',
                'qualification' => 'FCPS(Psychiatry), MD',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 800,
                'experience_years' => 20,
                'rating' => 4.8,
                'license_number' => 'MD-PSY-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:30:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Expert in anxiety, depression and psychotherapy.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. R. K. Saha',
                'email' => 'rk.saha@medicare.local',
                'phone' => '+8801712345721',
                'specialization' => 'Psychiatry',
                'qualification' => 'FCPS(Psychiatry), DPM',
                'hospital' => 'National Institute of Mental Health',
                'fee' => 600,
                'experience_years' => 12,
                'rating' => 4.5,
                'license_number' => 'MD-PSY-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:30:00',
                'break_end' => '12:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'NIMH, Dhaka',
                'bio' => 'Specialist in child psychiatry and behavioral disorders.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Kaniz Fatema',
                'email' => 'kaniz.fatema@medicare.local',
                'phone' => '+8801712345722',
                'specialization' => 'Psychiatry',
                'qualification' => 'MD(Psychiatry), FCPS',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 550,
                'experience_years' => 8,
                'rating' => 4.4,
                'license_number' => 'MD-PSY-003',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Expert in women mental health and postpartum depression.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Prof. Dr. M. R. H. B. Bhuiyan',
                'email' => 'bhuiyan@medicare.local',
                'phone' => '+8801712345723',
                'specialization' => 'Psychiatry',
                'qualification' => 'PhD(Psychiatry), FCPS',
                'hospital' => 'Sir Salimullah Medical College',
                'fee' => 700,
                'experience_years' => 18,
                'rating' => 4.7,
                'license_number' => 'MD-PSY-004',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:00:00',
                'max_appointments' => 10,
                'city' => 'Dhaka',
                'address' => 'SSMC, Dhaka',
                'bio' => 'Specialist in addiction medicine and substance abuse treatment.',
                'languages' => ['en', 'bn'],
            ],

            // Gastroentology Department (4 doctors)
            [
                'name' => 'Prof. Dr. H. N. K. Sarker',
                'email' => 'hnk.sarker@medicare.local',
                'phone' => '+8801712345724',
                'specialization' => 'Gastroenterology',
                'qualification' => 'FCPS(Gastro), MD(Gastro), FRCP',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 1000,
                'experience_years' => 20,
                'rating' => 4.9,
                'license_number' => 'MD-GASTRO-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Leading gastroenterologist with expertise in advanced endoscopy.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. M. A. Malek',
                'email' => 'ma.malek@medicare.local',
                'phone' => '+8801712345725',
                'specialization' => 'Gastroenterology',
                'qualification' => 'MD(Gastro), FCPS',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 750,
                'experience_years' => 12,
                'rating' => 4.6,
                'license_number' => 'MD-GASTRO-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 15,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Specialist in liver diseases and hepatitis treatment.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Kazi M. Hasan',
                'email' => 'kazi.hasan@medicare.local',
                'phone' => '+8801712345726',
                'specialization' => 'Gastroenterology',
                'qualification' => 'FCPS(Gastro), MD',
                'hospital' => 'Sir Salimullah Medical College',
                'fee' => 700,
                'experience_years' => 10,
                'rating' => 4.5,
                'license_number' => 'MD-GASTRO-003',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'SSMC, Dhaka',
                'bio' => 'Expert in IBD and inflammatory bowel disease treatment.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. A. K. M. Hassan',
                'email' => 'hassan@medicare.local',
                'phone' => '+8801712345727',
                'specialization' => 'Gastroenterology',
                'qualification' => 'MD(Gastro), FCPS',
                'hospital' => 'Square Hospitals Ltd.',
                'fee' => 850,
                'experience_years' => 14,
                'rating' => 4.7,
                'license_number' => 'MD-GASTRO-004',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'Square Hospitals, Dhaka',
                'bio' => 'Specialist in pancreatic diseases and ERCP procedures.',
                'languages' => ['en', 'bn'],
            ],

            // Nephrology Department (3 doctors)
            [
                'name' => 'Prof. Dr. Harun-or-Rashid',
                'email' => 'harun.rashid@medicare.local',
                'phone' => '+8801712345728',
                'specialization' => 'Nephrology',
                'qualification' => 'FCPS(Nephrology), MD, FRCP',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 900,
                'experience_years' => 18,
                'rating' => 4.8,
                'license_number' => 'MD-NEPHR-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Expert in kidney transplantation and dialysis management.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. M. Z. H. Khan',
                'email' => 'mzh.khan@medicare.local',
                'phone' => '+8801712345729',
                'specialization' => 'Nephrology',
                'qualification' => 'MD(Nephrology), FCPS',
                'hospital' => 'National Kidney Foundation',
                'fee' => 750,
                'experience_years' => 12,
                'rating' => 4.6,
                'license_number' => 'MD-NEPHR-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:00:00',
                'break_end' => '13:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'NKF, Dhaka',
                'bio' => 'Specialist in hypertension and kidney disease management.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Bidhan Chandra Sarker',
                'email' => 'bidhan.sarker@medicare.local',
                'phone' => '+8801712345730',
                'specialization' => 'Nephrology',
                'qualification' => 'FCPS(Nephrology), MD',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 700,
                'experience_years' => 10,
                'rating' => 4.5,
                'license_number' => 'MD-NEPHR-003',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Expert in glomerulonephritis and proteinuria treatment.',
                'languages' => ['en', 'bn'],
            ],

            // Surgery Department (4 doctors)
            [
                'name' => 'Prof. Dr. A. K. M. A. Hasan',
                'email' => 'akma.hasan@medicare.local',
                'phone' => '+8801712345731',
                'specialization' => 'General Surgery',
                'qualification' => 'FCPS(Surgery), MS(Surgery), FACS',
                'hospital' => 'Bangabandhu Sheikh Mujib Medical University',
                'fee' => 900,
                'experience_years' => 22,
                'rating' => 4.9,
                'license_number' => 'MD-SURG-001',
                'available_days' => ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday'],
                'start_time' => '10:00:00',
                'end_time' => '16:00:00',
                'break_start' => '13:00:00',
                'break_end' => '14:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'BSMMU, Shahbagh, Dhaka',
                'bio' => 'Expert in laparoscopic and minimally invasive surgery.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. M. H. R. Sarker',
                'email' => 'mhr.sarker@medicare.local',
                'phone' => '+8801712345732',
                'specialization' => 'General Surgery',
                'qualification' => 'FCPS(Surgery), DSO',
                'hospital' => 'Dhaka Medical College Hospital',
                'fee' => 650,
                'experience_years' => 14,
                'rating' => 4.6,
                'license_number' => 'MD-SURG-002',
                'available_days' => ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
                'start_time' => '09:00:00',
                'end_time' => '14:00:00',
                'break_start' => '11:30:00',
                'break_end' => '12:00:00',
                'max_appointments' => 15,
                'city' => 'Dhaka',
                'address' => 'DMCH, Dhaka',
                'bio' => 'Specialist in breast surgery and thyroid surgery.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. Fazle Mahmud',
                'email' => 'fazle.mahmud@medicare.local',
                'phone' => '+8801712345733',
                'specialization' => 'General Surgery',
                'qualification' => 'MS(Surgery), FCPS',
                'hospital' => 'Sir Salimullah Medical College',
                'fee' => 600,
                'experience_years' => 10,
                'rating' => 4.4,
                'license_number' => 'MD-SURG-003',
                'available_days' => ['monday', 'wednesday', 'friday'],
                'start_time' => '08:00:00',
                'end_time' => '13:00:00',
                'break_start' => '10:30:00',
                'break_end' => '11:00:00',
                'max_appointments' => 14,
                'city' => 'Dhaka',
                'address' => 'SSMC, Dhaka',
                'bio' => 'Expert in trauma surgery and emergency procedures.',
                'languages' => ['en', 'bn'],
            ],
            [
                'name' => 'Dr. ASM Faruk',
                'email' => 'faruk@medicare.local',
                'phone' => '+8801712345734',
                'specialization' => 'General Surgery',
                'qualification' => 'FCPS(Surgery), FASCRS',
                'hospital' => 'Square Hospitals Ltd.',
                'fee' => 750,
                'experience_years' => 16,
                'rating' => 4.7,
                'license_number' => 'MD-SURG-004',
                'available_days' => ['tuesday', 'thursday', 'saturday'],
                'start_time' => '10:00:00',
                'end_time' => '15:00:00',
                'break_start' => '12:30:00',
                'break_end' => '13:00:00',
                'max_appointments' => 12,
                'city' => 'Dhaka',
                'address' => 'Square Hospitals, Dhaka',
                'bio' => 'Specialist in colorectal surgery and anal diseases.',
                'languages' => ['en', 'bn'],
            ],
        ];

        $createdCount = 0;
        $scheduleCount = 0;
        $skippedCount = 0;

        foreach ($doctors as $doctorData) {
            // Check if doctor already exists by license number
            $existingDoctor = Doctor::where('license_number', $doctorData['license_number'])->first();
            
            if ($existingDoctor) {
                // Just update the schedules for existing doctor
                $user = $existingDoctor->user;
                $specialization = $existingDoctor->specialization;
                $doctor = $existingDoctor;
                
                // Delete existing schedules and create new ones
                DoctorSchedule::where('doctor_id', $doctor->id)->delete();
                
                foreach ($doctorData['available_days'] as $day) {
                    DoctorSchedule::create([
                        'doctor_id' => $doctor->id,
                        'day_of_week' => $day,
                        'start_time' => $doctorData['start_time'],
                        'end_time' => $doctorData['end_time'],
                        'break_start' => $doctorData['break_start'],
                        'break_end' => $doctorData['break_end'],
                        'max_appointments' => $doctorData['max_appointments'],
                        'is_active' => true,
                    ]);
                    $scheduleCount++;
                }
                
                $skippedCount++;
                echo "⏭️  Skipped (exists): " . $doctorData['name'] . " (schedules updated)\n";
                continue;
            }

            // Create or update user
            $user = User::updateOrCreate(
                ['email' => $doctorData['email']],
                [
                    'name' => $doctorData['name'],
                    'phone' => $doctorData['phone'],
                    'password' => Hash::make('doctor123'),
                    'is_active' => true,
                    'is_doctor' => true,
                ]
            );

            // Find or create specialization (use name as unique identifier)
            // First check if it exists by name, or find by slug
            $slug = strtolower(str_replace([' ', '&'], ['-', 'and'], $doctorData['specialization']));
            $specialization = Specialization::where('name', $doctorData['specialization'])->first();
            
            if (!$specialization) {
                // Check if a specialization with this slug already exists
                $existingBySlug = Specialization::where('slug', $slug)->first();
                if ($existingBySlug) {
                    // Update the existing one with new name
                    $existingBySlug->update(['name' => $doctorData['specialization']]);
                    $specialization = $existingBySlug;
                } else {
                    $specialization = Specialization::create([
                        'name' => $doctorData['specialization'],
                        'slug' => $slug,
                        'description' => 'Specialist in ' . $doctorData['specialization'],
                    ]);
                }
            } else {
                // Update the existing specialization
                $specialization->update([
                    'slug' => $slug,
                    'description' => 'Specialist in ' . $doctorData['specialization'],
                ]);
            }

            // Create or update doctor (use license_number as unique identifier)
            $doctor = Doctor::updateOrCreate(
                ['license_number' => $doctorData['license_number']],
                [
                    'user_id' => $user->id,
                    'specialization_id' => $specialization->id,
                    'license_number' => $doctorData['license_number'],
                    'qualification' => $doctorData['qualification'],
                    'experience_years' => $doctorData['experience_years'],
                    'hospital_clinic' => $doctorData['hospital'],
                    'consultation_fee' => $doctorData['fee'],
                    'rating' => $doctorData['rating'],
                    'total_reviews' => rand(50, 300),
                    'languages' => $doctorData['languages'],
                    'available_days' => $doctorData['available_days'],
                    'start_time' => $doctorData['start_time'],
                    'end_time' => $doctorData['end_time'],
                    'slot_duration' => 30,
                    'is_available' => true,
                    'is_verified' => true,
                    'city' => $doctorData['city'],
                    'address' => $doctorData['address'],
                    'bio' => $doctorData['bio'],
                ]
            );

            // Update user with doctor_id
            $user->update(['doctor_id' => $doctor->id]);

            // Delete existing schedules for this doctor and create new ones
            DoctorSchedule::where('doctor_id', $doctor->id)->delete();

            // Create schedules for each available day
            foreach ($doctorData['available_days'] as $day) {
                DoctorSchedule::create([
                    'doctor_id' => $doctor->id,
                    'day_of_week' => $day,
                    'start_time' => $doctorData['start_time'],
                    'end_time' => $doctorData['end_time'],
                    'break_start' => $doctorData['break_start'],
                    'break_end' => $doctorData['break_end'],
                    'max_appointments' => $doctorData['max_appointments'],
                    'is_active' => true,
                ]);
                $scheduleCount++;
            }

            $createdCount++;
            echo "✅ Added/Updated: " . $doctorData['name'] . " (" . $doctorData['specialization'] . ") - " . count($doctorData['available_days']) . " days\n";
        }

        echo "\n" . str_repeat('=', 70) . "\n";
        echo "Successfully imported {$createdCount} doctors with {$scheduleCount} schedules!\n";
        if ($skippedCount > 0) {
            echo "({$skippedCount} doctors already existed, schedules updated)\n";
        }
        echo str_repeat('=', 70) . "\n";
        echo "Login credentials: doctor email / doctor123\n";
    }
}
